### ISSUE TITLE
TypeError: nsfw is not a function

### ISSUE THREAD

**Issue by Arcanemagus** [smashwilson/watcher-stress#5]
On a whim I decided to try using the `nsfw` backend with `--use nsfw` and got the following error:
```
>> ERROR <<
TypeError: nsfw is not a function
    at NsfwFacade.start (C:\Users\abneyl\Documents\GitHub\watcher-stress\build\facade.js:60:21)
    at Promise.all.roots.map (C:\Users\abneyl\Documents\GitHub\watcher-stress\build\cli.js:13:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Using https://github.com/smashwilson/watcher-stress/commit/5b969c2d157aaf7a45a88fa014bc8f6c23a973b9.

**Comment by Arcanemagus** [comment]
I'm not entirely sure what the problem is myself just looking at the code. If `nsfw` is installed it looks like it should work, and it at least _appears_ to be installed:
```sh
> npm ls --depth=0
@smashwilson/watcher-stress@1.0.8 C:\Users\abneyl\Documents\GitHub\watcher-stress
+-- @atom/watcher@0.0.4
+-- babel-cli@6.24.1
+-- babel-preset-env@1.6.0
+-- colors@1.1.2
+-- commander@2.9.0
+-- human-format@0.8.0
+-- mz@2.6.0
+-- nsfw@1.0.15
+-- standard@10.0.3
`-- temp@0.8.3
```

**Comment by Arcanemagus** [comment]
Turns out that this is caused by building `nsfw` under `npm_config_debug="true"`. Running `npm rebuild nsfw` outside of that environment will fix this if `watcher-stress` itself was built using that.

Thanks for the idea of trying that @smashwilson!
