### ISSUE TITLE
TypeError: available is not a function

### ISSUE THREAD

**Issue by Arcanemagus** [smashwilson/watcher-stress#9]
I'm getting this while trying to run ~~`watcher-stress --help`~~ `watcher-stress` on 487fd1f0f65fdfedd6e4a9943813f798ab14f8cb:

```
const watcherNames = available().join(', ');
                     ^

TypeError: available is not a function
    at Object.<anonymous> (C:\Users\abneyl\Documents\GitHub\watcher-stress\build\index.js:22:22)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by smashwilson** [comment]
@Arcanemagus I had this a few times this morning. Try `rm -r build/` and then `npm install` to re-transpile the source.

(I split `facade.js` into a directory `facade/index.js`... but Babel doesn't delete transpiled files that aren't there any more, and `require()` prefers the old `facade.js`.)

**Comment by Arcanemagus** [comment]
Ha! I just discovered that was the issue, putting up a quick PR that fixes this.
